---
# Variables here are applicable to all host groups

env:
  GENERAL_TZ: "Europe/Moscow"
  PLEX_HOST_CONFIG_DIR: "~/nucbox/plex/config"
  PLEX_HOST_TRANSCODE_DIR: "~/nucbox/plex/transcode"
  PLEX_HOST_DATA_DIR: "~/nucbox/plex/data"
  PLEX_HOST_SUFFIX: ""
  HTPCM_HOST_CONFIG_DIR: "~/nucbox/htpcm/config"
deployment_app_root: "/opt/nucbox"
app_repo: "https://github.com/bstrochkov/nucbox.git"