---
# Variables here are applicable to development hosts only

env:
  GENERAL_TZ: "Europe/Moscow"
  PLEX_HOST_CONFIG_DIR: "/Users/b.strochkov/nucbox/plex/config"
  PLEX_HOST_TRANSCODE_DIR: "/Users/b.strochkov/nucbox/plex/transcode"
  PLEX_HOST_DATA_DIR: "/Users/b.strochkov/nucbox/plex/data"
  PLEX_HOST_SUFFIX: "-dev"
  HTPCM_HOST_CONFIG_DIR: "/Users/b.strochkov/nucbox/htpcm/config"
deployment_app_root: "/Users/b.strochkov/opt/nucbox"