version: '3'
services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
    - TZ=${TIMEZONE}
    network_mode: host
    volumes:
    - ./volumes/plex/config:/config
    - ./volumes/plex/transcode:/transcode
    - ./volumes/media:/data
  qbittorrent:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    environment:
    - TZ=${TIMEZONE}
    - UMASK_SET=022
    - WEBUI_PORT=1080
    volumes:
    - ./volumes/qbittorrent/config:/config
    - ./volumes/downloads:/downloads
    - ./volumes/media:/media
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
    - 80:80
    volumes:
    - ./volumes/nginx/html:/usr/share/nginx/html
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d
  vouch:
    image: voucher/vouch-proxy
    restart: unless-stopped
    volumes:
      - ./volumes/vouch/config:/config
      - ./volumes/vouch/data:/data
  netdata:
    image: netdata/netdata
    hostname: sysmon.borisa.net # set to fqdn of host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PGID=999

