version: '3'
services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
    - TZ=${TIMEZONE}
    network_mode: host
    volumes:
    - ./volumes/plex/config:/config
    - ./volumes/plex/transcode:/transcode
    - ./volumes/media:/data
  qbittorrent:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=${TIMEZONE}
    - UMASK_SET=022
    - WEBUI_PORT=1080
    volumes:
    - ./volumes/qbittorrent/config:/config
    - ./volumes/downloads:/downloads
    - ./volumes/media:/media
  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./volumes/nginx/html:/usr/share/nginx/html
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d

