version: '3'
services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
    - TZ=${TIMEZONE}
    network_mode: host
    volumes:
    - ./volumes/plex/config:/config
    - ./volumes/plex/transcode:/transcode
    - ./volumes/media:/data
  htpcm:
    image: linuxserver/htpcmanager
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=${TIMEZONE}
    volumes:
    - ./volumes/htpcm/config:/config
  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./volumes/nginx/html:/usr/share/nginx/html

