version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: nucbox-plex${PLEX_HOST_SUFFIX}
    network_mode: host
    environment:
      - TZ=${GENERAL_TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${PLEX_HOST_CONFIG_DIR}:/config
      - ${PLEX_HOST_TRANSCODE_DIR}:/transcode
      - ${PLEX_HOST_DATA_DIR}:/data
  htpcm:
    container_name: htpcm
    image: linuxserver/htpcmanager
    ports:
      - 8085:8085/tcp
    environment:
      - TZ=${GENERAL_TZ}
    volumes:
      - ${HTPCM_HOST_CONFIG_DIR}:/config