version: '3'
services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
    - TZ=${TIMEZONE}
    network_mode: host
    volumes:
    - ./volumes/plex/config:/config
    - ./volumes/plex/transcode:/transcode
    - ./volumes/media:/data
  htpcm:
    image: linuxserver/htpcmanager
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=${TIMEZONE}
    volumes:
    - ./volumes/htpcm/config:/config
  couchpotato:
    image: linuxserver/couchpotato
    restart: unless-stopped
    network_mode: host
    environment:
    - TZ=${TIMEZONE}
    - UMASK_SET=022
    volumes:
    - ./volumes/couchpotato/config:/config
    - ./volumes/couchpotato/downloads:/downloads
    - ./volumes/media:/movies
  nginx:
    image: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./volumes/nginx/html:/usr/share/nginx/html
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d

