version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: nucbox-plex${PLEX_HOST_SUFFIX}
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${GENERAL_TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${PLEX_HOST_CONFIG_DIR}:/config
      - ${PLEX_HOST_TRANSCODE_DIR}:/transcode
      - ${PLEX_HOST_DATA_DIR}:/data
  htpcm:
    container_name: htpcm
    image: linuxserver/htpcmanager
    ports:
      - 8085:8085/tcp
    environment:
      - TZ=${GENERAL_TZ}
    volumes:
      - ${HTPCM_HOST_CONFIG_DIR}:/config