---
# Uses:
# - env
# - deployment_app_root

- name: "Cloning the repository"
  git:
    repo: "{{ app_repo }}"
    dest: "{{ deployment_app_root }}"
    update: no
  become: yes

- name: "Making dcmp executable"
  file:
    path: "{{ deployment_app_root }}/dcmp"
    mode: u+x,g+x,o+x

- import_tasks: chown_app_root.yml

- import_tasks: get_plex_claim_token.yml
  when: env.PLEX_CLAIM_TOKEN is undefined

- import_tasks: configure_and_run.yml