---
# Deploy to production stage

#TODO: Init inventory file

- import_playbook: install.yml

- name: "Deploying nucbox app"
  hosts: "{{ override_hosts | default('prod') }}"

  tasks:

  - import_tasks: roles/nucbox_server/tasks/fill_env_file.yml
  - import_tasks: roles/nucbox_server/tasks/restart_docker.yml

