---
# Deploy to production stage
# Use:
# - override_hosts
# - app_repo
# - deployment_app_root
# - ansible_user

#TODO: Init inventory file

- import_playbook: install.yml

- name: "Deploying nucbox app"
  hosts: "{{ override_hosts | default('prod') }}"
  vars:
    _current_path: "."

  tasks:

  - command: git clean -fd
    args:
      chdir: "{{ deployment_app_root }}"
    when: deploy_current_dir is undefined

  - name: "Updating the app"
    git:
      repo: "{{ app_repo }}"
      dest: "{{ deployment_app_root }}"
      update: yes
      force: yes
    when: deploy_current_dir is undefined

  - name: "Updating the app from current directory"
    synchronize:
      src: "{{ _current_path | realpath }}/"
      dest: "{{ deployment_app_root }}"
    when: deploy_current_dir is defined

  - import_tasks: roles/nucbox_server/tasks/configure_and_run.yml

